apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
  - ../../base
images:
  - name: docker.io/your-dockerhub-username/auth-service
    newTag: v1.0.0
  - name: docker.io/your-dockerhub-username/product-service
    newTag: v1.0.0
  - name: docker.io/your-dockerhub-username/cart-service
    newTag: v1.0.0
  - name: docker.io/your-dockerhub-username/order-service
    newTag: v1.0.0
  - name: docker.io/your-dockerhub-username/notification-service
    newTag: v1.0.0
  - name: docker.io/your-dockerhub-username/api-gateway
    newTag: v1.0.0
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
