apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ecommerce
data:
  PORT: "4000"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  PRODUCT_SERVICE_URL: "http://product-service:4002"
  CART_SERVICE_URL: "http://cart-service:4003"
  ORDER_SERVICE_URL: "http://order-service:4004"
  NOTIFICATION_SERVICE_URL: "http://notification-service:4005"
