apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
- ../../base
images:
  - name: docker.io/akshaykumarshetty/auth-service
    newTag: dev
  - name: docker.io/akshaykumarshetty/product-service
    newTag: dev
  - name: docker.io/akshaykumarshetty/cart-service
    newTag: dev
  - name: docker.io/akshaykumarshetty/order-service
    newTag: dev
  - name: docker.io/akshaykumarshetty/notification-service
    newTag: dev
  - name: docker.io/akshaykumarsetty/api-gateway
    newTag: dev
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
